"""Add relate useres to companies

Revision ID: 13cc0e2e82de
Revises: 5d308426c452
Create Date: 2025-09-01 16:47:39.964756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13cc0e2e82de'
down_revision: Union[str, Sequence[str], None] = '5d308426c452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'companies', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'user_uid')
    # ### end Alembic commands ###
